[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
[Cassette: 'workers/api_key_info/characterAPI'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :path, :host], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system, :erb=>true}
[webmock] Handling request: [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] (disabled: false)
  [Cassette: 'workers/api_key_info/characterAPI'] Initialized HTTPInteractionList with request matchers [:method, :path, :host] and 1 interaction(s): { [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] => [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"] }
  [Cassette: 'workers/api_key_info/characterAPI'] Checking if [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] matches [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] using [:method, :path, :host]
    [Cassette: 'workers/api_key_info/characterAPI'] method (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] path (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
    [Cassette: 'workers/api_key_info/characterAPI'] host (matched): current request [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] vs [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
  [Cassette: 'workers/api_key_info/characterAPI'] Found matching interaction for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx] at index 0: [200 "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>201"]
[webmock] Identified request type (stubbed_by_vcr) for [post https://api.eveonline.com/account/Apikeyinfo.xml.aspx]
